# Generated by Django 3.2.18 on 2023-04-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Ação/FII'), ('investment_fund', 'fundo de investimento'), ('fixed income', 'renda fixa')], max_length=50)),
                ('usertag1', models.CharField(blank=True, max_length=50)),
                ('usertag2', models.CharField(blank=True, max_length=50)),
                ('usertag3', models.CharField(blank=True, max_length=50)),
                ('native_currency', models.CharField(max_length=5)),
                ('native_market', models.CharField(max_length=5)),
                ('business_market', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateField()),
                ('index', models.CharField(max_length=15)),
                ('coupon_period_in_months', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Ação/FII'), ('investment_fund', 'fundo de investimento'), ('fixed income', 'renda fixa')], max_length=50)),
                ('usertag1', models.CharField(blank=True, max_length=50)),
                ('usertag2', models.CharField(blank=True, max_length=50)),
                ('usertag3', models.CharField(blank=True, max_length=50)),
                ('native_currency', models.CharField(max_length=5)),
                ('native_market', models.CharField(max_length=5)),
                ('business_market', models.CharField(blank=True, max_length=50)),
                ('days_to_application_cutoff', models.CharField(max_length=50)),
                ('days_to_redemption_cutoff', models.CharField(max_length=50)),
                ('days_to_application_liquidation', models.CharField(max_length=50)),
                ('days_to_redemption_liquidation', models.CharField(max_length=50)),
                ('fund_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Ação/FII'), ('investment_fund', 'fundo de investimento'), ('fixed income', 'renda fixa')], max_length=50)),
                ('usertag1', models.CharField(blank=True, max_length=50)),
                ('usertag2', models.CharField(blank=True, max_length=50)),
                ('usertag3', models.CharField(blank=True, max_length=50)),
                ('native_currency', models.CharField(max_length=5)),
                ('native_market', models.CharField(max_length=5)),
                ('business_market', models.CharField(blank=True, max_length=50)),
                ('ticker', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('external_ticker', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
